name: Build Snapshot (1.19)

on: [pull_request, push, workflow_dispatch]
jobs:
  validate-gradle:
    name: "Validate Gradle wrapper"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gradle/wrapper-validation-action@v1

  build:
    name: "Build"
    runs-on: ubuntu-20.04
    if: |
      !contains(github.event.pull_request.title, '[ci skip]')
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu

      - name: Setup and Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace --no-daemon

      - name: Setting mod version
        run: |
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^archives_base_name= >> $GITHUB_ENV
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^minecraft_version= >> $GITHUB_ENV
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^mod_version= >> $GITHUB_ENV
      - name: Create package name
        run: echo "package_name=[$minecraft_version] $archives_base_name-$mod_version-SNAPSHOT.r$GITHUB_RUN_ATTEMPT" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.package_name }}
          path: build/libs/*[0-9].jar
